# Generated by Django 5.1.3 on 2025-05-29 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CalculatorField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('field_type', models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('dropdown', 'Dropdown')], default='number', max_length=50)),
                ('required', models.BooleanField(default=True)),
                ('calculator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='calculators.calculator')),
            ],
        ),
        migrations.AddField(
            model_name='calculator',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculators', to='calculators.category'),
        ),
    ]
