# Generated by Django 5.1.3 on 2025-06-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
