# Generated by Django 5.1.3 on 2025-06-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0002_category_slug_alter_calculator_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='template',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
