# Generated by Django 5.1.3 on 2025-06-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0003_calculator_template_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
